embedding:
  method: "POST"
  url: "https://llm.api.cloud.yandex.net/foundationModels/v1/textEmbedding"

  headers:
    Authorization: "Bearer {iam_token}"
    Content-Type: "application/json"

  body:
    modelUri: "emb://{folder_id}/text-search-query/latest"
    
  path:
    text: ["text"]
    embedding: ["embedding"]