services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    restart: unless-stopped
    command: sh -c 'redis-server /etc/redis.conf --requirepass "$$REDIS__PASSWORD"'
    volumes:
      - redis_data:/data
      - ${COMPOSE__REDIS_CONFIG_PATH:-./config/bot/redis.conf}:/etc/redis.conf:ro
    env_file:
      - env/bot.env

  db:
    image: pgvector/pgvector:pg17
    container_name: database_server
    restart: unless-stopped
    environment:
      POSTGRES_DB: faq_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: orchestrator_server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB__HOST: db
    env_file:
      - env/orchestrator.env
    volumes:
      - ${COMPOSE__LOGGING_PATH:-./config/logging.yml}:/app/config/logging.yml:ro
      - ${COMPOSE__ORCHESTRATOR_REQUESTS_PATH:-./config/orchestrator/requests.yml}:/app/config/requests.yml:ro
  
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot_server
    restart: unless-stopped
    depends_on:
      - orchestrator
      - redis
    environment:
      REDIS__HOST: redis
      ORCHESTRATOR_CLIENT__BASE_URL: http://orchestrator:8000
    env_file:
      - env/bot.env
    ports:
      - "8080:8080"
    volumes:
      - ${COMPOSE__LOGGING_PATH:-./config/logging.yml}:/app/config/logging.yml:ro
      - ${COMPOSE__BOT_CONSTANTS_PATH:-./config/bot/constants.example.yml}:/app/config/constants.yml:ro
      - ${COMPOSE__BOT_MESSAGES_PATH:-./config/bot/messages.example.yml}:/app/config/messages.yml:ro
      - ${COMPOSE__BOT_COMMANDS_PATH:-./config/bot/commands.example.yml}:/app/config/commands.yml:ro
      - ${COMPOSE__BOT_CERTIFICATE_PATH:-./config/bot/webhook.pem}:/app/config/webhook.pem:ro

volumes:
  postgres_data:
  redis_data:
