services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS__PASSWORD:-password} --appendonly yes
    volumes:
      - redis_data:/data
    env_file:
      - bot.env

  db:
    image: pgvector/pgvector:pg17
    container_name: database_server
    restart: always
    environment:
      POSTGRES_DB: faq_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: orchestrator_server
    restart: always
    depends_on:
      - db
    environment:
      DB__HOST: db
    env_file:
      - orchestrator.env
    volumes:
      - ${PATHS__LOGGING:-./config/logging.yml}:/app/config/logging.yml:ro
      - ${PATHS__REQUESTS:-./config/orchestrator/requests.yml}:/app/config/requests.yml:ro
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot_server
    restart: always
    depends_on:
      - orchestrator
      - redis
    environment:
      REDIS__HOST: redis
      ORCHESTRATOR__BASE_URL: http://orchestrator:8000
    env_file:
      - bot.env
    volumes:
      - ${PATHS__LOGGING:-./config/logging.yml}:/app/config/logging.yml:ro
      - ${PATHS__CONSTANTS:-./config/bot/constants.yml}:/app/config/constants.yml:ro
      - ${PATHS__MESSAGES:-./config/bot/messages.yml}:/app/config/messages.yml:ro
      - ${PATHS__COMMANDS:-./config/bot/commands.yml}:/app/config/commands.yml:ro

volumes:
  postgres_data:
  redis_data:
