SETTINGS = "settings"

CREATE = "create"
GET = "get"
UPDATE = "update"
DELETE = "delete"
LIST = "list"

USERS = (SETTINGS, f"{SETTINGS}.users")

USERS_CREATE = (USERS[1], f"{USERS[1]}.{CREATE}")
USERS_GET = (USERS[1], f"{USERS[1]}.{GET}")
USERS_UPDATE = (USERS[1], f"{USERS[1]}.{UPDATE}")
USERS_DELETE = (USERS[1], f"{USERS[1]}.{DELETE}")
USERS_LIST = (USERS[1], f"{USERS[1]}.{LIST}")

QUESTIONS = (SETTINGS, f"{SETTINGS}.questions")

QUESTIONS_CREATE = (QUESTIONS[1], f"{QUESTIONS[1]}.{CREATE}")
QUESTIONS_GET = (QUESTIONS[1], f"{QUESTIONS[1]}.{GET}")
QUESTIONS_UPDATE = (QUESTIONS[1], f"{QUESTIONS[1]}.{UPDATE}")
QUESTIONS_DELETE = (QUESTIONS[1], f"{QUESTIONS[1]}.{DELETE}")
QUESTIONS_LIST = (QUESTIONS[1], f"{QUESTIONS[1]}.{LIST}")

FORMULATIONS = (SETTINGS, f"{SETTINGS}.formulations")

FORMULATIONS_CREATE = (FORMULATIONS[1], f"{FORMULATIONS[1]}.{CREATE}")
FORMULATIONS_GET = (FORMULATIONS[1], f"{FORMULATIONS[1]}.{GET}")
FORMULATIONS_UPDATE = (FORMULATIONS[1], f"{FORMULATIONS[1]}.{UPDATE}")
FORMULATIONS_DELETE = (FORMULATIONS[1], f"{FORMULATIONS[1]}.{DELETE}")
FORMULATIONS_LIST = (FORMULATIONS[1], f"{FORMULATIONS[1]}.{LIST}")
