start_template: >
      Hello, {username}! I will help you find the answer — just send a question
      or choose one of the most popular ones below!

failed_template: "{exception}. Try to reformulate it and ask again"

commands:
  help: You can get support in the channel <a href="https://t.me/fincubes">t.me/fincubes</a> or via email <a href="mailto:mail@fincubes.ru">mail@fincubes.ru</a>.

exceptions:
  search:
    empty_result: "It seems that we failed to understand the question"